### ISSUE TITLE
NTT.py ^ vs ** ? 

### ISSUE THREAD

**Issue by anshul92101** [Jyun-Neng/PyFHE#1]
In the following lines, shouldn't the operator ^ actually be ** ? 

 if rev_i > i:
                coeff ^= _poly[rev_i]
                _poly[rev_i] ^= coeff
                coeff ^= _poly[rev_i]
                _poly[i] = coeff

These lines give error on running also upon changing them to ** the program gets frozen.

**Comment by Jyun-Neng** [comment]
Sorry for the late reply. It seems that there are some bugs while doing homomorphic multiplication. There are no problems of NTT algorithm.
This project is out of date. It is better to read [HElib](https://github.com/shaih/HElib).
